# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the Health Research Data Catalogue API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"
info:
  version: "{VERSION}"
  title: Health Research Data Catalogue API
  description: |
    
    ## Overview
    Use this API to retrieve information suitable for publication in a health research data catalogue. 

    You can:
    * get a list of datasets
    * get details for a specific dataset 

    You cannot currently use this API to:
    * retrieve datasets as a bulk transfer
    * retrieve dataset feeds

    You can get the following information for each dataset:
    * characteristics such as: publisher, keywords, coverage, provenance, access, format, standards and data utility
    * logical descriptions of field-level data

    ### API scope
    Current scope is limited to information about national health-related datasets (such as description, size of the population contained within that dataset and the legal basis for access) that can help researchers and innovators decide whether a dataset could be useful to their research and help them to make further health discoveries.

    ## Who can use this API
    This API can only be used where there is a legal basis to do so. Make sure you have a valid use case before you go too far with your development. You must do this before you can go live (see ‘Onboarding’ below).

    ## Related APIs
    There are no related APIs.

    ## API status and roadmap
    This API is initially for use by Health Data Research (HDR) UK developers with other use cases to follow later.

    This API is in [alpha](https://digital.nhs.uk/developer/guides-and-documentation/reference-guide#api-status), meaning:
    - the API is available in our sandbox and integration test environments
    - the API is not yet available for production use
    - we might make breaking changes, but only if we cannot avoid it, and we'll give advance notice

    To see our roadmap, or to suggest, comment or vote on features for this API, see our [interactive product backlog](https://nhs-digital-api-management.featureupvote.com/?order=popular&filter=all&tag=reasonable-adjustment-flag#controls).
    If you have any other queries, please [contact us](https://digital.nhs.uk/developer/help-and-support).

    ## Technology
    This API is [RESTful](https://digital.nhs.uk/developer/guides-and-documentation/api-technologies-at-nhs-digital#basic-rest-apis). 

    ## Network access

    This API is available on the internet and, indirectly, on the [Health and Social Care Network (HSCN)](https://digital.nhs.uk/services/health-and-social-care-network). 
    For more details see [Network access for APIs](https://digital.nhs.uk/developer/guides-and-documentation/network-access-for-apis).

    ## Security and authorisation
    
    This API is [application-restricted](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis), meaning we authenticate and authorise the calling application and we do not authenticate or authorise the end user.
    
    Although we don't authenticate or authorise the end user, for some APIs we do require the calling application to do it 'locally'. For other APIs we don't require the end user to be authenticated or authorised, or even to be present.
    
    We support the following security patterns for application-restricted APIs:
    - [Application-restricted RESTful API - API key authentication](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation/application-restricted-restful-apis-api-key-authentication)
   
    For more details, see [application-restricted APIs](https://digital.nhs.uk/developer/guides-and-documentation/security-and-authorisation#application-restricted-apis).

    ## Environments and testing
    | Purpose                                | Base URL                                            |
    | ---------------------------------------|-----------------------------------------------------|
    | Sandbox                                | `https://sandbox.api.service.nhs.uk/health-research-data-catalogue`|
    | Integration test                       | `https://int.api.service.nhs.uk/health-research-data-catalogue`    |
    | Production                             | Not yet available                                         |
    
    ### Sandbox testing
    Details of the sandbox environment to follow.
 
    ### Integration testing
    Details of the integration environment to follow.
 
    ## Onboarding
    You need to get your software approved by us before it can go live with this API. We call this onboarding. The onboarding process can sometimes be quite long, so it’s worth planning well ahead.

    More details on the onboarding process to follow.
  contact:
    name: Health Research Data Catalogue API Support
    url: 'https://digital.nhs.uk/developer/help-and-support'
    email: api.management@nhs.net
servers:
  - url: 'https://sandbox.api.service.nhs.uk/health-research-data-catalogue'
    description: Sandbox environment
  - url: 'https://int.api.service.nhs.uk/health-research-data-catalogue'
    description: Integration test environment.   
x-spec-publication:
  try-this-api:
    disabled: false
  operation-order:
  - operations:
    - method: GET
      path: /datasets
    - method: GET
      path: '/datasets/{id}' 
paths:
  /datasets:    
    get:
      summary: Get a list of datasets
      operationId: get-datasets-list      
      description: |

        <div class="nhsd-m-emphasis-box"><div class="nhsd-a-box nhsd-a-box--border-blue"><div class="nhsd-m-emphasis-box__content-box">
            <p class="nhsd-t-body-s nhsd-t-word-break">Note: the sandbox API is under construction so Try this API responses don't work in this release. </p>
        </div></div>&nbsp;&nbsp;</div>

        ## Overview
        Use this endpoint to list a summary of all Health Research Data Catalogue 'published' datasets.

        ## Summary dataset metadata returned
        
        The summary dataset metadata returned is not the full set of metadata that is returned on a retrieval of a dataset by dataset identifier.
        The following dataset metadata is included:
        * schema
        * type
        * identifier
        * description
        * version
        * date issued
        * date modified

      parameters:
       - $ref: '#/components/parameters/RequestID'
       - $ref: '#/components/parameters/CorrelationID'           
       # - in: query
       #   name: q
       #   description: query
       #   schema:
       #     type: string  
#        - in: query
#          name: offset
#          description: The first result to retrieve. If not set (offset = 0), results will be retrieved starting from row 0.
#          schema:
#            type: integer
#            format: int32
# #           default: "0"                
#        - in: query
#          name: limit
#          description: The maximum number of results to retrieve. If not set (limit = 0), the default limit will be used.
#          schema:
#            type: integer
#            format: int32
# #           default: "0"       
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    minimum: 1
                # type: object
                # properties:
                #   query:
                #     type: object
                #     properties:
                #       # q:
                #       #   type: string
                #       #   description: TBC
                #       #   example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
                #       total:
                #         type: string
                #         example: 181
                      # limit:
                      #   type: string
                      #   description: The maximum number of results to retrieve
                      #   example: 1000
                      # offset:
                      #   type: string
                      #   description: The first result to retrieve
                      #   example: 0
                  '@schema':    
                    type: object
                    properties:
                        type:
                          type: string
                          description: JSON document type
                          example: Dataset
                        version:
                          type: string 
                          description: Dataset schema version
                          "$ref": "components/schemas/pdc.dataset.definitions.schema.yaml#/definitions/semver" 
                        url: 
                          type: string
                          description: Dataset URL
                          anyOf:
                          # - "$ref": "components/schemas/pdc.dataset.definitions.schema.yaml#/definitions/uuidv4"
                          - "$ref": "components/schemas/pdc.dataset.definitions.schema.yaml#/definitions/url"
                  items:
                    type: array
                    items:
                      type: object
                      properties:
                        # '@schema':
                        #   type: string
                        #   description: HDR UK Dataset schema
                        #   example: https://hdruk.github.io/schemata/schema/dataset/latest/dataset.schema.json
                        # type:
                        #   type: string
                        #   description: JSON document type
                        #   example: Dataset
                        identifier:
                          type: string
                          description: Dataset identifier
                          anyOf:
                          - "$ref": "components/schemas/pdc.dataset.definitions.schema.yaml#/definitions/uuidv4"
                          - "$ref": "components/schemas/pdc.dataset.definitions.schema.yaml#/definitions/url"
                        persistent identifier:
                          type: string
                          description: Dataset persistent identifier
                          anyOf:
                          - "$ref": "components/schemas/pdc.dataset.definitions.schema.yaml#/definitions/uuidv4"
                          - "$ref": "components/schemas/pdc.dataset.definitions.schema.yaml#/definitions/url"
                        name:
                          type: string
                          description: Dataset name
                          example: Civil Registration - Deaths
                        description:
                          type: string
                          description: Dataset description
                          example: Deaths registration data (all deaths in England and Wales) collected from The Registrar General for England and Wales. Record-level patient dataset, where a record represents one death registration. 
                        # version:
                        #   type: string 
                        #   description: Dataset schema version
                        #   "$ref": "components/schemas/pdc.dataset.definitions.schema.yaml#/definitions/semver"
                        self:
                          type: string
                          description: Self link
                          example: https://api.service.nhs.uk/health-research-data-catalogue/datasets/dd5f0174-575f-4f4c-a4fc-b406aab953d9
                        issued:
                          type: string
                          description: Dataset metadata creation date
                          format: date-time
                          example: 2020-08-05T14:35:59Z
                        modified:
                          type: string
                          description: Dataset metadata modification date
                          format: date-time
                          example: 2021-01-28T14:15:46Z
                        # source:
                        #   description: The source of the data extraction
                        #   type: string 
                        #   "$ref": "components/schemas/pdc.dataset.definitions.schema.yaml#/definitions/source"               
                        #   example: OTHER
              example:  
                $ref: components/examples/dataset-list-example1.json            
        "4XX":
          description: |
            An error occurred as follows:
            
            | HTTP status | Error code                 | Description |
            | ----------- | -------------------------- | --------------------------------------------- |
            | 400         | INVALID_RESOURCE_ID        | Invalid dataset id. |
            | 401         | ACCESS_DENIED              | Access token missing, invalid or expired, or calling application not configured for this operation. |
            | 404         | RESOURCE_NOT_FOUND         | No dataset resources found. |
    
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/OperationOutcome-2.yaml'
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: structure
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: ACCESS_DENIED
                          display: access has been denied to process this request

        "500":
          description: Internal Server Error
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationErrorOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: unknown
                    details:
                      coding:
                        - system: "https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode"
                          version: '1'
                          code: UNKNOWN_ERROR
                          display: Unknown Error
                    diagnostics: "An unknown error occurred processing this request. Contact us for assistance diagnosing this issue: https://digital.nhs.uk/developer/help-and-support."

        "503":
          description: |
            The request timed out during processing. This does not imply the request has failed or been rejected. Error code: `SERVICE_UNAVAILABLE`.

            Re-send the request after the time specified in the `Retry-After` header using the same `X-Request-ID` value.
          headers:
            RetryAfter:
              $ref: 'components/schemas/RetryAfter.yaml'
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/OperationOutcome-2.yaml'
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: timeout
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: SERVICE_UNAVAILABLE
                          display: Service unavailable
                    diagnostics: "The downstream domain processing has not completed within the configured timeout period. Using the same 'X-Request-ID' header, retry your request after the time specified by the 'Retry-After' response header."

  '/datasets/{id}':
    get:
      summary: Get details for a specific dataset 
      operationId:  get-datasets-id    
      description: |

        <div class="nhsd-m-emphasis-box"><div class="nhsd-a-box nhsd-a-box--border-blue"><div class="nhsd-m-emphasis-box__content-box">
            <p class="nhsd-t-body-s nhsd-t-word-break">Note: the sandbox API is under construction so Try this API responses don't work in this release. </p>
        </div></div>&nbsp;&nbsp;</div>

        ## Overview
        Use this endpoint to get dataset details from the Health Research Data Catalogue for a given dataset identifier (UUID).
  
        ## Dataset metadata returned

        | Data element | Conformance                | Description |
        | ------------ | -------------------------- | --------------------------------------------- |
        | identifier   | Required                   | System dataset identifier. |
        | version      | Required                   | Dataset metadata version. |
        | revisions    | Required                   | Revisions of Dataset metadata. Includes the Semantic Version of the dataset and URL endpoint to obtain the version. |
        | issued       | Required                   | Dataset Metadata Creation Date. |
        | modified     | Required                   | Dataset Metadata Modified Date. |
        | summary      | Required                   | Summary metadata must be completed by Data Custodians onboarding metadata into the Innovation Gateway MVP. |
        | documentation|                            | Documentation can include a rich text description of the dataset or links to media such as documents, images, presentations, videos or links to data dictionaries, profiles or dashboards. Organisations are required to confirm that they have permission to distribute any additional media. |
        | coverage     |                            | This information includes attributes for geographical and temporal coverage, cohort details etc. to enable a deeper understanding of the dataset content so that researchers can make decisions about the relevance of the underlying data. |
        | provenance   |                            | Provenance information allows researchers to understand data within the context of its origins and can be an indicator of quality, authenticity and timeliness. |
        | accessibility| Required                   | Accessibility information allows researchers to understand access,  usage, limitations, formats, standards and linkage or interoperability with toolsets. |
        | enrichmentAndLinkage|                     | This section includes information about related datasets that may have previously been linked, as well as indicating if there is the opportunity to link to other datasets in the future. If a dataset has been enriched and/or derivations, scores and existing tools are available this section allows providers to indicate this to researchers. |
        | observations | Required                   | Multiple observations about the dataset may be provided and users are expected to provide at least one observation (1..*). Examples detailed in next section. |

 
        ### Observations

        Multiple observations about the dataset may be provided and users
        are expected to provide at least one observation (1..*). We will be supporting
        the schema.org observation model (https://schema.org/Observation) with default values. Users will be encouraged to provide their own statistical populations as the project progresses.   Examples: 

        | Statistical Population | Population Size  | Measured Property | Observation Date | Population Description |
        |------------------------| ---------------- | ----------------- | ---------------- | ---------------------- |
        | Persons                | 32937            | Count             | 2017             | Events relating to period between April - Sept 2017 |
        | Events                 | 14900000         | Count             | 15/01/2021       | Number of unique death registrations since 1993 in England and Wales |
        | Findings               | 17,891           | Count             | 2020-09-03       | Cancer Germline - Number of genomes |

      parameters:
       - $ref: '#/components/parameters/RequestID'
       - $ref: '#/components/parameters/CorrelationID' 
       - in: path
         name: id
         description: ID of the Dataset
         schema:
           type: string
           format: uuid 
           example: 'dd5f0174-575f-4f4c-a4fc-b406aab953d9'   
         required: true              
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: components/schemas/pdc.dataset.schema.yaml
              example:
                $ref: components/examples/hdruk.json                

        "4XX":
          description: |
            An error occurred as follows:
            
            | HTTP status | Error code                 | Description |
            | ----------- | -------------------------- | --------------------------------------------- |
            | 400         | INVALID_RESOURCE_ID        | Invalid dataset id. |
            | 401         | ACCESS_DENIED              | Access token missing, invalid or expired, or calling application not configured for this operation. |
            | 404         | RESOURCE_NOT_FOUND         | No dataset resources found. |
    
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/OperationOutcome-2.yaml'
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: structure
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: ACCESS_DENIED
                          display: access has been denied to process this request

        "500":
          description: Internal Server Error
          content:
            application/fhir+json:
              schema:
                $ref: components/schemas/OperationErrorOutcome.yaml
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: unknown
                    details:
                      coding:
                        - system: "https://fhir.nhs.uk/CodeSystem/Spine-ErrorOrWarningCode"
                          version: '1'
                          code: UNKNOWN_ERROR
                          display: Unknown Error
                    diagnostics: "An unknown error occurred processing this request. Contact us for assistance diagnosing this issue: https://digital.nhs.uk/developer/help-and-support."
 
        "503":
          description: |
            The request timed out during processing. This does not imply the request has failed or been rejected. Error code: `SERVICE_UNAVAILABLE`.

            Re-send the request after the time specified in the `Retry-After` header using the same `X-Request-ID` value.
          headers:
            RetryAfter:
              $ref: 'components/schemas/RetryAfter.yaml'
          content:
            application/fhir+json:
              schema:
                $ref: 'components/schemas/OperationOutcome-2.yaml'
              example:
                resourceType: OperationOutcome
                issue:
                  - severity: error
                    code: timeout
                    details:
                      coding:
                        - system: 'https://fhir.nhs.uk/R4/CodeSystem/Spine-ErrorOrWarningCode'
                          version: '1'
                          code: SERVICE_UNAVAILABLE
                          display: Service unavailable
                    diagnostics: "The downstream domain processing has not completed within the configured timeout period. Using the same 'X-Request-ID' header, retry your request after the time specified by the 'Retry-After' response header."                    
components:
  parameters:                                                 
    CorrelationID:
      in: header
      name: X-Correlation-ID
      required: false
      description: |
        An optional ID which you can use to track transactions across multiple systems. It can take any value, but we recommend avoiding `.` characters.

        Mirrored back in a response header.
      schema:
        type: string
        example: 11C46F5F-CDEF-4865-94B2-0EE0EDCC26DA
    RequestID:
      in: header
      name: X-Request-ID
      required: false
      description: |
        A globally unique identifier (GUID) for the request, which we use to de-duplicate repeated requests and to trace the request if you contact our helpdesk.

        Must be a universally unique identifier (UUID) (ideally version 4).

        Mirrored back in a response header.

        If you re-send a failed request, use the same value in this header.
      schema:
        type: string
        pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
        example: 60E0B220-8136-4CA5-AE46-1D97EF59D068